### ISSUE TITLE
Please optimize your ping usage

### ISSUE THREAD

**Issue by Hex4dec** [JimmyHelp/JimmyAnims#2]
I have all pings turned on (for debugging), and there was a user with your Figura library. The chat is filled with useless pings that could be done clientside like JimmyAmins_Using, JimmyAmins_cFly, setChat, I don't even know what JimmyAmins_Distance is. All of the 3 I mention can be done client-side, please read the Player APIs fully before writing another line of code.

**Comment by JimmyHelp** [comment]
1. I already optimized ping usage in the latest version of jimmyanims. i just forgot to upload it to github
2. You are really stupid if you think keybinds, creative flying, and reach distance can be done client side. reach the wiki and the host api fully before writing another line of code
